apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: prod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu
            args: ['/bin/sh', '-c', 'date; echo Hello from the Kubernetes cluster']
          restartPolicy: Never