apiVersion: batch/v1
kind: Job
metadata:
  name: math
  namespace: prod
  labels:
    app: math
spec:
  completions: 3
  parallelism: 3    # jobs will run in parallel. We can remove it and make sequential
  template:
    metadata:
      name: math
      labels:
        app: math
    spec:
      containers:
      - name: math
        image: ubuntu
        command: ['expr', '3', '+', '2']
      restartPolicy: Never